config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users
  notify_to :users,
    with_devise: :users,
    controller: 'users/notifications_with_devise'

  devise_for :admins,
    controllers: {
      sessions: 'admin/sessions'
    },
    path: 'admin',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }

  # static pages
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'policy' => 'static_pages#policy'
  get 'rule' => 'static_pages#rule'
  get 'terms' => 'static_pages#terms'

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  resources :posts, except: [:edit, :update, :delete], concerns: :paginatable do
    resources :comments, only: [:create]
  end

  resources :users, only: [:show]
  resources :bulletins, only: [:show]

  namespace :admin do
    root 'dashboard#index'
    post 'metrics', to: 'dashboard#save_metrics'

    resources :admins, only: [:index]
    resources :posts, only: [:index, :show]
    resources :bulletins, only: [:index, :new, :create]
  end
end

app/models/bulletin.rb
class Bulletin < ApplicationRecord

  belongs_to :user
  validates :user_id, presence: true
  validates :body, presence: true

  # acts_as_notifiable configures your model as ActivityNotification::Notifiable
  # with parameters as value or custom methods defined in your model as lambda or symbol.
  # The first argument is the plural symbol name of your target model.
  acts_as_notifiable :users,
    # Notification targets as :targets is a necessary option
    # Set to notify to author and users commented to the article, except comment owner self
    targets: ->(bulletin, key) {
      [User.find_by(id: bulletin.user_id)]
    }
end

# == Schema Information
#
# Table name: comments
#
#  id             :integer          not null, primary key
#  body           :text             not null
#  user_id        :integer
#
# Indexes
#

app/controllers/admin/bulletins_controller.rb
class Admin::BulletinsController < ApplicationController
  layout 'admin'

  before_action :authenticate_admin!

  def index
    @bulletins = Bulletin.all
  end

  def new
    @bulletin = Bulletin.new
  end

  def create
    @bulletin = Bulletin.new(bulletin_params)

    if @bulletin.save
      ActivityNotification::Notification.notify(:users, @bulletin)

      redirect_to admin_bulletins_path
    else
      render 'new'
    end
  end

  private

  def bulletin_params
    params.require(:bulletin).permit(:user_id, :body)
  end
end

app/controllers/bulletins_controller.rb
class BulletinsController < ApplicationController

  def show
    @bulletin = Bulletin.find(params[:id])
  end
end

app/views/admin/bulletins/index.html.erb
<h2>ヒアリング管理 <span> <%= link_to "新規作成", new_admin_bulletin_path %> </span> </h2>
<div class="table-responsive">
  <table class="table table-striped table-responsive">
    <thead>
      <tr>
        <th>ID</th>
        <th>内容</th>
      </tr>
    </thead>
    <tbody>
      <% @bulletins.each do |bulletin| %>
        <tr>
          <td><%= link_to bulletin.id, bulletin_path(bulletin) %></td>
          <td><%= bulletin.body %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/bulletins/new.html.erb
<h2>新規ヒアリング</h2>
<% if notice %><div class=""><p class=""><%= notice %></p></div><% end %>
<% if alert %><div class=""><p class=""><%= alert %></p></div><% end %>
<div class="col-sm-offset-4 col-sm-4 col-xs-12">
  <%= form_for(@bulletin, url: admin_bulletins_path(@bulletin), html: {class: "form"}) do |f| %>
    <div class="form-group">
      <%= f.label :user_id %><br />
      <%= f.number_field :user_id, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :body %><br />
      <%= f.text_area :body, autocomplete: "off", class: "form-control" %>
    </div>

    <%= f.submit "送信", class: "btn btn-primary btn-lg" %>
  <% end %>

</div>