config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users
  notify_to :users,
    with_devise: :users,
    controller: 'users/notifications_with_devise'

  devise_for :admins,
    controllers: {
      sessions: 'admin/sessions'
    },
    path: 'admin',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }

  # static pages
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'policy' => 'static_pages#policy'
  get 'rule' => 'static_pages#rule'
  get 'terms' => 'static_pages#terms'

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  resources :posts, except: [:edit, :update, :delete], concerns: :paginatable do
    resources :comments, only: [:create]
  end

  resources :users, only: [:show]
  resources :bulletins, only: [:show]

  namespace :admin do
    root 'dashboard#index'
    post 'metrics', to: 'dashboard#save_metrics'

    resources :admins, only: [:index]
    resources :posts, only: [:index, :show]
    resources :bulletins, only: [:index, :new, :create]
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  layout 'admin'

  before_action :authenticate_admin!
  before_action :set_metrics, only: [:index, :save_metrics]

  def index
    # @data = KpiManager.curate_data
  end

  def save_metrics
    @metric = Metric.new
    @metric.allu = @all_users
    @metric.mau = @monthly_active_users
    @metric.wau = @weekly_active_users
    @metric.biau = @bi_active_users
    @metric.dau = @daily_active_users
    @metric.weekly_new_users = @new_users
    @metric.weekly_new_all_posts = @all_posts
    @metric.weekly_new_uniq_posts = @uniq_posts
    @metric.weekly_new_all_comments = @comments
    @metric.weekly_new_posts_ratio = @posts_ratio.round(2)
    @metric.weekly_new_comments_ratio = @comments_ratio.round(2)
    @metric.weekly_new_all_conv = @mm
    @metric.weekly_new_uniq_conv = @uniq_mm

    if @metric.save
      Slack::MetricsSavedNotifier.notify(
        Slack::Template::MetricsSavedMessage.format(@metric)
      )

      redirect_to admin_root_path
    else
      redirect_to admin_root_path
    end
  end

  private
  def set_metrics
    # TODO: うんちこーどだけどまたすぐかわりそうなのでとりあえずこれで
    # Concerned Entities
    # # Active Users
    @all_users = User.all.size
    @monthly_active_users = User.all.where(updated_at: 30.days.ago..Time.now).size
    @weekly_active_users = User.all.where(updated_at: 7.days.ago..Time.now).size
    @bi_active_users = User.all.where(updated_at: 3.days.ago..Time.now).size
    @daily_active_users = User.all.where(updated_at: 1.days.ago..Time.now).size

    # # New Users
    new_users = User.all.where(created_at: 7.days.ago..Time.now)
    @new_users = new_users.size

    # # Posts by New users
    posts_a = []
    r_posts_a = []
    r_comments_a = []
    new_users.each do |new_user|
      posts = new_user.posts.pluck(:id)
      commented_posts = new_user.commented_posts.pluck(:id)

      # for ratio
      r_posts_a = r_posts_a + posts
      r_comments_a = r_comments_a + commented_posts

      actions = posts + commented_posts
      posts_a = posts_a + actions.uniq
    end
    @all_posts = posts_a.size
    @uniq_posts = posts_a.uniq.size

    # # CommentedPosts by new users
    @comments = r_comments_a.size

    # % Posts and CommentedPosts / # ""
    r_all = r_posts_a.size + r_comments_a.size
    @posts_ratio = r_all == 0 ? 0 : r_posts_a.size / r_all.to_f
    @comments_ratio = r_all == 0 ? 0 : r_comments_a.size / r_all.to_f

    # # Posts and CommentedPosts with more than two contributers including the User
    mm_a = []
    new_users.each do |new_user|
      user_convs = []
      commented_posts = new_user.commented_posts
      if commented_posts.present?
        commented_posts.each do |post|
          if post.commented_users.size >= 2
            user_convs << post.id
          end
        end
      end
      mm_a = mm_a + user_convs.uniq
    end
    @mm = mm_a.size
    @uniq_mm = mm_a.uniq.size

    @today = Time.now.strftime('%Y年%m月%d日')
    @week_ago = 7.days.ago.strftime('%Y年%m月%d日')
  end
end

app/views/admin/dashboard/index.html.erb
<h2>ダッシュボード <span><%= link_to "保存", admin_metrics_path, :method => :post %></span></h2>

<h4 style="margin-top: 30px;"><%= @week_ago %> ~<br> <%= @today %></h4>
<br>
<hr>
<h5 style="margin-top: 30px; color: red;"><p>ユーザー数</p></h4>
<div class="table-responsive">
  <table class="table table-striped table-responsive">
    <thead>
      <tr>
        <th>ALL</th>
        <th>MAU</th>
        <th>WAU</th>
        <th>BiAU</th>
        <th>DAU</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @all_users %>
        <td><%= @monthly_active_users %>
        <td><%= @weekly_active_users %>
        <td><%= @bi_active_users %>
        <td><%= @daily_active_users %>
      </tr>
    </tbody>
  </table>
</div>
<br>
<hr>
<h5 style="margin-top: 30px; color: red;"><p>ユーザーリテンション</p></h4>
[wip] 30日前のデータがたまるまでまつ．GAを見てくれ． (エンゲージメントは mixpanelよさそう)<br>
Ce - Cn / Cs, for e is end, s is start, n is new
WAUe - Un / WAUsがよいのかな．．？
<br>
<br>
<hr>
<h5 style="margin-top: 30px; color: red;"><p>ユーザーファネル</p></h4>
<div class="table-responsive">
  <table class="table table-striped table-responsive">
    <thead>
      <tr>
        <th>新規ユーザーの...</th>
        <th>登録数 / 訪問数(GA)</th>
        <th>アクション数 / 登録数</th>
        <th>マジモメ数 / アクション数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">週間</th>
        <td><%= @new_users %> / GAの新規訪問数</td>
        <td><%= @new_users == 0 ? 'NA' : ((@all_posts / @new_users.to_f) * 100).round(2) %>%</td>
        <td><%= @all_posts == 0 ? 'NA' : ((@mm / @all_posts.to_f) * 100).round(2) %>%</td>
      </tr>
    </tbody>
  </table>
</div>

<br>
<hr>
<h5 style="margin-top: 30px; color: red;"><p>集計した数値</p></h4>
<div class="table-responsive">
  <table class="table table-striped table-responsive">
    <thead>
      <tr>
        <th></th>
        <th>新規訪問数</th>
        <th>新規ユーザー登録数</th>
        <th>新規ユーザーアクション数</th>
        <!-- <th>新規ユーザーアクション内訳 (投稿 : コメント)</th> -->
        <th>新規ユーザーマジモメ数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">週間</th>
        <td>NA</td>
        <td><%= @new_users %></td>
        <td><%= @all_posts %></td>
        <!-- <td><%= @posts_ratio.round(2) %> : <%= @comments_ratio.round(2) %></td> -->
        <td><%= @mm %></td>
      </tr>
    </tbody>
  </table>
</div>

<br>
<hr>
<h5 style="margin-top: 30px; color: red;"><p>ユーザーファネル 別バージョン</p></h4>
<div class="table-responsive">
  <table class="table table-striped table-responsive">
    <thead>
      <tr>
        <th>新規の...</th>
        <th>ユーザー登録数 / 訪問数(GA)</th>
        <th>アクション数 / ユーザー登録数</th>
        <th>ユニークマジモメ数 / ユニークアクション数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">週間</th>
        <td><%= @new_users %> / GAの新規訪問数</td>
        <td><%= @new_users == 0 ? 'NA' : ((@all_posts / @new_users.to_f) * 100).round(2) %>%</td>
        <td><%= @uniq_posts == 0 ? 'NA' : ((@uniq_mm / @uniq_posts.to_f) * 100).round(2) %>%</td>
      </tr>
    </tbody>
  </table>
</div>
<span>新規ユーザーユニークアクション数: <%= @uniq_posts %> | 新規ユーザーユニークマジモメ数: <%= @uniq_mm %></span>
<br>
<hr>