config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users
  notify_to :users,
    with_devise: :users,
    controller: 'users/notifications_with_devise'

  devise_for :admins,
    controllers: {
      sessions: 'admin/sessions'
    },
    path: 'admin',
    path_names: {
      sign_in: 'login',
      sign_out: 'logout'
    }

  # static pages
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'policy' => 'static_pages#policy'
  get 'rule' => 'static_pages#rule'
  get 'terms' => 'static_pages#terms'

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  resources :posts, except: [:edit, :update, :delete], concerns: :paginatable do
    resources :comments, only: [:create]
  end

  resources :users, only: [:show]
  resources :bulletins, only: [:show]

  namespace :admin do
    root 'dashboard#index'
    post 'metrics', to: 'dashboard#save_metrics'

    resources :admins, only: [:index]
    resources :posts, only: [:index, :show]
    resources :bulletins, only: [:index, :new, :create]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :commented_users, through: :comments, source: :user
  belongs_to :user, touch: true

  acts_as_notification_group printable_name: ->(post) { "投稿" }
  # has_enumeration_for :generated_by, with: PostGeneratedBy, create_helpers: { prefix: true }

  validates :user_id, presence: true
  validates :body, presence: true

  scope :order_by_default, -> {
    order(id: :desc)
  }

  scope :since, ->(time) {
    where("created_at > ?", time)
  }

  scope :order_by_last_active_at, -> {
    order(updated_at: :desc)
  }

  def title
    # cut out title here
  end
end

# == Schema Information
#
# Table name: posts
#
#  id             :integer          not null, primary key
#  author         :string
#  body           :text             not null
#
# Indexes
#
#

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'admin'

  before_action :authenticate_admin!

  def index
    @posts = Post.all.order_by_default
  end

  def show
    @post = Post.find(params[:id])
  end

  # def new
  #   @post = Post.new
  # end
  #
  # def create
  #   @post = Post.new(post_params)
  #
  #   @post.author = helpers.simple_nkf(post_params[:author])
  #   @post.body = helpers.simple_nkf(post_params[:body])
  #
  #   if @post.save
  #     Slack::PostCreatedNotifier.notify(Slack::Template::PostCreatedMessage.format(@post))
  #
  #     redirect_to @post
  #   else
  #     render 'new'
  #   end
  # end
  #
  # private
  #
  # def post_params
  #   params.require(:post).permit(:author, :body)
  # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # decorates_assigned :posts
  before_action :sign_in_user, only: [:new, :create]

  def index
    @posts = Post.all.order_by_last_active_at.includes(:user).page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.order("created_at asc").includes(:user)
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.body = helpers.simple_nkf(post_params[:body])

    if @post.save
      Slack::PostCreatedNotifier.notify(
        Slack::Template::PostCreatedMessage.format(@post)
      ) unless admin_signed_in?

      redirect_to @post
    else
      render 'new'
    end
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end

  def sign_in_user
    unless user_signed_in?
      redirect_to new_user_registration_path
    end
  end
end

app/views/posts/_comment_form.html.erb
<div class="commentForm">
  <%= form_for([@post, @post.comments.build]) do |f| %>
    <div class="row between-xs commentFormWrapper">
      <div class="col-xs-9 commentForm__itemWrapper">
        <div class="commentForm__form">
          <textarea id="commentForm__textarea" placeholder="コメントする" name="comment[body]" rows="1"></textarea>
        </div>
      </div>
      <div class="col-xs-3 commentForm__itemWrapper">
        <div class="commentForm__item">
          <div class="commentForm__submit">
            <div id="btn-commentForm__submit" class="btn btn--primary">
              <%= f.button type: 'submit', data: { disable_with: "..."} do %>
                <%= image_tag('feather-message-circle.svg', :alt => "header burger") %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<script>
  autosize(document.querySelectorAll('textarea'));
</script>

app/views/posts/_posts.html.erb
<ul class="postList">
  <% @posts.each do |post| %>
    <li class="postItem">
      <div class="o-media">
        <div class="row start-xs">
          <div class="col-xs-2">
            <div class="o-media__img">
              <%= link_to user_path(post.user) do %>
                <%= image_tag(post.user.decorate.avatar, :class => "test", :alt => "user icon") %>
              <% end %>
            </div>
          </div>
          <div class="col-xs-10" style="padding-left: 0.2rem;">
            <div class="o-media__bd">
              <div class="postContent">
                <div class="postContent__meta">
                  <%= link_to user_path(post.user) do %>
                    <span class="postContent__author"><%= post.decorate.author %></span>
                  <% end %>
                  <span class="postContent__datetime"><%= post.decorate.last_active_at %></span>
                </div>
                <div class="postContent__body">
                  <%= link_to post_path(post), class: 'noSelect' do %>
                    <p><%= auto_link(simple_format(hbr(post.body))) %></p>
                  <% end %>
                </div>
                <div class="postContent__commentsCount">
                  <span>コメント <%= post.comments.size %></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/posts/index.html.erb
<%= render partial: 'shared/margin_top' %>

<main id="main">
  <div class="row center-xs">
    <div class="col-xs-12 col-md-9 col-lg-6">
      <% if notice %>
        <div class="mainFlashMessage">
          <p class=""><%= notice %></p>
        </div>
      <% end %>
      <% if alert %>
        <div class="mainFlashMessage">
          <p class=""><%= alert %></p>
        </div>
      <% end %>
      <% if user_signed_in? %>
        <%= render partial: 'shared/alpha', locals: { lede_text: 'こんにちは、'+ current_user.decorate.username + '。寂しい時はみんなに頼りましょう( ´ ▽ ` )' } %>
      <% else %>
        <%= render partial: 'shared/alpha', locals: { lede_text: '投稿は被っても大丈夫。寂しい時は話を聞いてもらいましょう(*^^*)' } %>
      <% end %>
      <section class="pageSection">
        <div class="homeFeed">
          <%= render :partial => 'posts', :object => @posts %>
          <p class="i-pagination">
            <%= link_to_next_page(@posts, 'もっと見る', :remote => true) %>
          </p>
        </div>
      </section>
      <% if user_signed_in? %>
        <div id="floatingContainer">
          <%= link_to new_post_path, class: "floatingAction__item noSelect" do %>
            <%= image_tag "talk-logo.png" %>
          <% end %>
        </div>
      <% else %>
        <div id="floatingContainer">
          <%= link_to new_user_registration_path, class: "floatingAction__item noSelect" do %>
            <%= image_tag "talk-logo.png" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</main>
<script>
  $(function() {
    // Configure infinite table
    return $('.postList').infinitePages({
      debug: true,
      context: '#main',
      loading() {
        return $(this).text('...');
      },
      error() {
        return $(this).button('エラーが起こりました。');
      }
    });
  });

  $('.mainFlashMessage').delay(4000).fadeOut(800);
</script>

app/views/posts/index.js.erb
// Append new data
$("<%=j render(:partial => 'posts', :object => @posts) %>")
  .appendTo($(".postList"));

// Update pagination link
<% if @posts.last_page? %>
  $('.i-pagination').html("終わり。");
<% else %>
  $('.i-pagination')
    .html("<%=j link_to_next_page(@posts, 'もっと見る', :remote => true) %>");
<% end %>

app/views/posts/new.html.erb
<script>
  $(function() {
    $('#header').hide();
  });
</script>

<%= form_for(@post) do |f| %>
  <div class="postForm animated fadeInUp test-animation">
    <div class="row center-xs">
      <div class="col-xs-12">
        <div class="postFormHeader">
          <div class="row between-xs postFormHeaderWrapper">
            <div class="col-xs-2 postFormHeader__itemWrapper">
              <%= link_to :back do %>
                <div class="postFormHeader__item">
                  <%= image_tag('feather-x.svg', :alt => "back") %>
                </div>
              <% end %>
            </div>
            <div class="col-xs-3 col-sm-2 col-md-1 postFormHeader__itemWrapper">
              <div class="postFormHeader__item">
                <%= f.button type: 'submit', class: 'btn btn--primary postForm__submit', data: { disable_with: "..."}  do %>
                  投稿
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <div class="postFormMain">
          <div class="postFormMain__form">
            <div class="row">
              <div class="col-xs-3">
                <div class="postFormMain__img">
                  <%= image_tag(current_user.decorate.avatar, :alt => "user icon") %>
                </div>
              </div>
              <div class="col-xs-9">
                <div class="postFormMain__bd">
                  <textarea id="postFormMain__textarea" placeholder="体験談や今の寂しさなど、気軽に投稿してみよう!" name="post[body]"></textarea>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
<script>
  autosize(document.querySelectorAll('textarea'));
</script>
<style>
  .test-animation{
    /* ５秒かけてアニメーションする */
    -webkit-animation-duration: 0.2s;
    animation-duration: 0.2s;
    /* 4秒待ってからアニメーションする */
    -webkit-animation-delay: 0s;
    animation-delay: 0s;
  }
</style>

app/views/posts/show.html.erb
<%= render partial: 'shared/margin_top' %>

<main id="main" style="margin-bottom: '200px;">
  <div class="row center-xs">
    <div class="col-xs-12 col-md-9 col-lg-6">
      <div class="postShow">
        <div class="o-media">
          <div class="row start-xs">
            <div class="col-xs-2">
              <div class="o-media__img">
                <%= link_to user_path(@post.user) do %>
                  <%= image_tag(@post.user.decorate.avatar, :alt => "user icon") %>
                <% end %>
              </div>
            </div>
            <div class="col-xs-10" style={{paddingLeft:'0.2rem'}}>
              <div class="o-media__bd">
                <div class="postContent">
                  <div class="postContent__meta">
                    <%= link_to user_path(@post.user) do %>
                      <span class="postContent__author"><%= @post.decorate.author %></span>
                    <% end %>
                    <span class="postContent__datetime"><%= @post.decorate.datetime %></span>
                  </div>
                  <div class="postContent__body">
                    <p><%= auto_link(simple_format(hbr(@post.body))) %></p>
                  </div>
                  <div class="postContent__commentsCount">
                    <span>コメント <%= @post.comments.size %></span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="postShowComments">
        <% if @comments.any? %>
          <h2 class="postShowComments__heading">コメント</h2>
          <ul class="commentList">
            <% @comments.each do |comment| %>
              <li class="commentItem">
                <div class="o-media">
                  <div class="row start-xs">
                    <div class="col-xs-2">
                      <div class="o-media__img  --small">
                        <%= link_to user_path(comment.user) do %>
                          <%= image_tag(comment.user.decorate.avatar, :alt => "user icon") %>
                        <% end %>
                      </div>
                    </div>
                    <div class="col-xs-10">
                      <div class="o-media__bd">
                        <div class="commentContent">
                          <div class="commentContent__meta">
                            <%= link_to user_path(comment.user) do %>
                              <span class="commentContent__author"><%= comment.decorate.author %></span>
                            <% end %>
                            <span class="commentContent__datetime"><%= comment.decorate.datetime %></span>
                          </div>
                          <div class="commentContent__body">
                            <p><%= auto_link(simple_format(hbr(comment.body))) %></p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
  <% if user_signed_in? %>
    <%= render :partial => "comment_form" %>
  <% else %>
    <%= link_to new_user_registration_path do %>
      <%= render :partial => "comment_form" %>
    <% end %>
  <% end %>
</main>